name: linux

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    env:
      ACE_ROOT: ${{ github.workspace }}/ACE
      TAO_ROOT: ${{ github.workspace }}/TAO
    steps:
    - name: checkout ACE/TAO
      uses: actions/checkout@v2
    - name: create $ACE_ROOT/ace/config.h
      run: |
        '#include "ace/config-linux.h"' > ${env:ACE_ROOT}/ace/config.h
      shell: pwsh
