name: linux

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-18.04
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    env:
      DOC_ROOT: ${{ github.workspace }}/FOO/ACE
    steps:
    - name: checkout ACE_TAO
      uses: actions/checkout@v2
      with:
        repository: DOCGroup/ACE_TAO
        path: ${env:DOC_ROOT}
    - name: Check file existence
      id: check_files
      uses: andstor/file-existence-action@v1
      with:
        files: "FOO/ACE/README.md"
