name: linux

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-18.04
          - os: ubuntu-20.04
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    env:
      ACE_ROOT: ${{ github.workspace }}/FOO/ACE
      TAO_ROOT: ${{ github.workspace }}/FOO/TAO
    steps:
    - name: checkout ACE
      uses: actions/checkout@v2
      with:
        repository: DOCGroup/ACE_TAO
        path: ${env:ACE_ROOT}
    - name: create $ACE_ROOT/ace/config.h
      run: |
        '#include "ace/config-linux.h"' > ${env:ACE_ROOT}/ace/config.h
      shell: pwsh
